### ISSUE TITLE
Decode delay after start sending bitstream to decoder

### ISSUE THREAD

**Issue by slavaman** [OtherCrashOverride/hello_videocube#3]
Hello! After sending h264 bitstream to decoder, we get result on a screen after 100-200ms delay. Then the delay between sending data to decoder and otput to screen is about 30 frames (tested with 2k resolution). Is it a bug or a feature? Can I reduce this latency? Is there any tune up features in amlcodec to get 1in=>1out without any delay?
Thnk you!

**Comment by OtherCrashOverride** [comment]
This repository is for the Raspberry Pi.  It was merged by and is now maintained by them.
